# Generated by Django 4.2.7 on 2024-03-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзину', 'verbose_name_plural': 'корзина'},
        ),
    ]
