# Generated by Django 4.2.7 on 2024-01-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=300, verbose_name='ФИО автора')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сведения об авторе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog_photo', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'author',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Жанр книги')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genre',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Язык книги')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'Языки',
                'db_table': 'language',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Издательство')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'издательство',
                'verbose_name_plural': 'Издательства',
                'db_table': 'publisher',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название книги')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('year_publication', models.CharField(max_length=4, verbose_name='Год издания')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Аннотация книги')),
                ('isbn', models.CharField(max_length=15, unique=True, verbose_name='ISBN  книги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog_images', verbose_name='Изображение обложки книги')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='Количество')),
                ('age_limit', models.PositiveSmallIntegerField(default=0, verbose_name='Ограничение по возрасту')),
                ('author', models.ManyToManyField(to='catalog.authors', verbose_name='Автор(ы) книги')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genres', verbose_name='Жанр книги')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.languages', verbose_name='Язык книги')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.publishers', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'ordering': ['title'],
            },
        ),
    ]
